#!/bin/sh /etc/rc.common

START=96
STOP=10

USE_PROCD=1

start_service() {
	config_load fancontrol

	local enabled
	config_get_bool enabled settings enabled 0
	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance
	procd_set_param command /usr/sbin/fancontrol-mtk
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger fancontrol
}
