#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@eqos[-1]
	add ucitrack eqos
	set ucitrack.@eqos[-1].init=eqos
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache /tmp/luci-indexcache.*
[ -n "$IPKG_INSTROOT" ] || {
	/etc/init.d/eqos enable >/dev/null 2>&1
	if [ "$(uci -q get eqos.config.enabled)" = 1 ]; then
		/etc/init.d/eqos restart >/dev/null 2>&1 || true
	else
		/etc/init.d/eqos stop >/dev/null 2>&1 || true
	fi
}
exit 0
