#!/bin/sh

. /lib/functions.sh
. /lib/functions/system.sh

if [ "$(board_name)" = "nradio,c2000-max" ]; then
	case "$ACTION" in
		ifup|ifdown|update) ;;
		*) exit 0 ;;
	esac
	[ ! -e /var/run/c2000max-port-role.switching ] || exit 0
	if [ "$INTERFACE" = "lan" ] && [ "$ACTION" = "ifdown" ]; then
		exec /etc/init.d/eqos stop
	fi
	[ "$INTERFACE" = "lan" ] || exit 0
	exec /etc/init.d/eqos reload
fi

[ "$ACTION" = "ifup" ] || exit 0
[ "$INTERFACE" = "lan" ] || exit 0
/etc/init.d/eqos start
