#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

service_triggers() {
	procd_add_reload_trigger "cnspeedtest"
}

start_service() {
	config_load cnspeedtest
	config_get_bool enabled main enabled 0

	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command /usr/libexec/cnspeedtest/run
	procd_set_param respawn 3600 5 5
	procd_set_param limits nofile="4096 4096"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
