#!/bin/sh /etc/rc.common
START=95
STOP=0
USE_PROCD=1

. /usr/share/qmodem/modem_util.sh

start_service() {
	:
}

stop_service() {
	procd_set_param timeout 30
	config_load qmodem
	config_foreach _soft_reboot modem-device
}

_soft_reboot() {
	config_section="$1"
	config_get soft_reboot $1 soft_reboot
	[ "$soft_reboot" != "1" ] && return 0

	config_get at_port $1 at_port
	config_get manufacturer $1 manufacturer
	config_get platform $1 platform
	config_get use_ubus $1 use_ubus 0
	[ -z "$at_port" ] && return 0

	for i in $(seq 1 3); do
		response=$(qmodem_tom_modem "$at_port" -o a -c "AT+CFUN=1,1")
		echo "$response" | grep -qi "ok" && break
		sleep 1
	done

	return 0
}
