#!/bin/sh /etc/rc.common

START=96
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /bin/sh -c 'sleep 10; exec /usr/sbin/c2000max-sim apply'
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	/usr/sbin/c2000max-sim apply >/dev/null 2>&1 &
}

service_triggers() {
	procd_add_reload_trigger c2000max
}
