#!/bin/sh /etc/rc.common

START=96
STOP=04
USE_PROCD=1

PROG=/usr/sbin/c2000max-service-worker

start_service()
{
	[ -x "$PROG" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param nice 10
	procd_set_param respawn 3600 5 5
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger adblock-fast netbird
}

reload_service()
{
	ubus call service signal \
		'{"name":"c2000max-service-worker","signal":10}' >/dev/null 2>&1 || true
}
