#!/bin/sh /etc/rc.common

START=97
STOP=10
USE_PROCD=1

start_service() {
	local mode
	if [ "$(uci -q get c2000max.led.enabled)" = 0 ]; then
		mode=off-lock
		/etc/init.d/qmodem_led stop >/dev/null 2>&1 || true
	fi
	procd_open_instance
	procd_set_param command /usr/sbin/c2000max-leds ${mode:+$mode}
	procd_set_param respawn 5 10 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger c2000max qmodem system
}
