#!/bin/sh /etc/rc.common

START=96
STOP=10
USE_PROCD=1

start_service()
{
	local local_enabled remote_enabled

	config_load c2000max_app
	config_get_bool local_enabled main local_enable 0
	config_get_bool remote_enabled main remote_enable 0

	[ "$local_enabled" = 1 ] || [ "$remote_enabled" = 1 ] || return 0

	procd_open_instance cache
	procd_set_param command /usr/sbin/c2000max-app-cache
	procd_set_param respawn 10 5 5
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_set_param limits core="0 0"
	procd_close_instance

	if [ "$local_enabled" = 1 ]; then
		procd_open_instance local
		procd_set_param command /usr/sbin/c2000max-app-local
		procd_set_param respawn 10 5 5
		procd_set_param stdout 0
		procd_set_param stderr 1
		procd_set_param limits core="0 0"
		procd_close_instance

		procd_open_instance http
		procd_set_param command /usr/sbin/c2000max-app-httpd
		procd_set_param respawn 10 5 5
		procd_set_param stdout 0
		procd_set_param stderr 1
		procd_set_param limits core="0 0"
		procd_close_instance
	fi

	[ "$remote_enabled" = 1 ] || return 0

	procd_open_instance bridge
	procd_set_param command /usr/sbin/c2000max-app-bridge
	procd_set_param respawn 10 5 5
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_set_param limits core="0 0"
	procd_close_instance

	procd_open_instance remote
	procd_set_param command /usr/sbin/c2000max-app-remote
	procd_set_param respawn 10 5 5
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_set_param limits core="0 0"
	procd_close_instance

	procd_open_instance reporter
	procd_set_param command /usr/sbin/c2000max-app-reporter
	procd_set_param respawn 30 5 3
	procd_set_param stdout 0
	procd_set_param stderr 1
	procd_set_param limits core="0 0"
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger c2000max_app
}
